#! /bin/bash

if [[ "$1" == "" ]] || [[ "$2" == "" ]] || [[ ! -a "$1" ]] ; then
    echo "Error: Please provide two parameters:" >&2
    echo "   1. The path to the input image" >&2
    echo "   2. The basename of the output images" >&2
    exit 2
fi

for i in 128 64 48 32; do 
    convert "$1" -resize "${i}x$i" "${2}_$i.png"
done
